### ISSUE TITLE
Update Schema for last non-detection

### ISSUE THREAD

**Issue by jchate6** [LCOGT/hermes#32]
We need to incorporate a way of marking a photometry datum as a last non-detection.

**Comment by jchate6** [comment]
This is a (kinda) required entry for TNS submissions of New Detections.

A few solutions were suggested, I'll try to summarize what I remember:

**Option 1:**
`last non-detection` Checkbox added to the photometry table (only allowed to be true for a single row)
if checked, cannot have both brightness and limiting brightness.
if checked, In submission, any brightness value mapped to limiting brightness along with error etc.
Call it a day, everyone gets a cookie.

**Option 2:**
Split Photometry into "Photometry: Detections" and Photometry: Non-Detections" in the GUI
Only offer limiting brightness non-detections, and brightness for detections.
Non-detections have checkbox (only allowed to be true for a single row) for `last non-detection`
everything dumped into the same Photometry section upon submission.
Go home, biscuit for everyone.

**Option 3:**
other more complicated options I don't remember the details of.
No pastries, only pain.

**Comment by jnation3406** [comment]
I believe this has been resolved in adding TNS submission support. Basically, in order to submit to TNS, you must submit at least one photometry that has a `limiting_brightness` value set. The most recent one according to `date_obs` will be used as the last non detection, so it is inferred for you. It has been merged to dev.
