### ISSUE TITLE
HERMES Prod filtered S230518h

### ISSUE THREAD

**Issue by phycodurus** [LCOGT/hermes#53]
Investigate why this happened, if possible.
tom-demo, SNEx2, and SAGUARO, ingested this event correctly.

**Comment by jnation3406** [comment]
We did the database swap in prod around this time, which meant starting with a fresh empty database, and I believe this alert came in just before that time so it was lost in the database swap. The earliest alerts I see in the current prod database are from 5/18 18:28 UTC, whereas the alert S230518h came in slightly before that time at 5/18 12:59. So I think the swap was done in between those times, and we lost the alert. It shouldn't happen again since we aren't planning to reset the database again.
